language: php
php:
- 5.3

before_script:
- git clone git://github.com/zendframework/ZendSkeletonApplication.git
- cd ZendSkeletonApplication
- php composer.phar install
- sudo cp ./ ZendSkeletonApplication/module/BrZend

script:
- cd ZendSkeletonApplication/module/BrZend/tests
- phpunit