language: php
php:
- 5.3

before_script:
- cd ../
- git clone git://github.com/zendframework/ZendSkeletonApplication.git
- cd ZendSkeletonApplication
- php composer.phar selfupdate
- php composer.phar install
- cd ../
- cd BrZend
- mkdir -p build/logs
- composer install --dev --no-interaction
- cd ..
- sudo cp -R BrZend/ ZendSkeletonApplication/module/BrZend
- cd ZendSkeletonApplication

script:
- cd ../ZendSkeletonApplication/module/BrZend/tests
- phpunit --coverage-clover ../build/logs/clover.xml

after_script:
- cd ..
- php vendor/bin/coveralls -v
