language: php
php:
- 5.3

before_script:
- cd ../
- git clone git://github.com/zendframework/ZendSkeletonApplication.git
- cd ZendSkeletonApplication
- php composer.phar selfupdate
- php composer.phar install
- cd ../
- sudo cp -R BrZend/ ZendSkeletonApplication/module/BrZend
- cd ZendSkeletonApplication
- composer require  satooshi/php-coveralls:dev-master
- mkdir -p build/logs

script:
- cd ../ZendSkeletonApplication/module/BrZend/tests
- phpunit 
after_script:
- cd ../../../
- php vendor/bin/coveralls -v
- cat build/logs/clover.xml
- php vendor/bin/coveralls:vl:jobs -c build/logs/clover.xml --dry-run