language: php
php:
- 5.3

before_script:
- cd ../
- git clone git://github.com/zendframework/ZendSkeletonApplication.git
- cd ZendSkeletonApplication
- php composer.phar selfupdate
- php composer.phar install
- cd ../
- sudo cp -R BrZend/ ZendSkeletonApplication/module/BrZend
- cd ZendSkeletonApplication
- composer require  satooshi/php-coveralls:dev-master

script:
- cd ../ZendSkeletonApplication/module/BrZend/tests
- phpunit
after_script:
- php ../../../vendor/bin/coveralls -v