language: php
php:
- 5.3

before_script:
- cd ../
- git clone git://github.com/zendframework/ZendSkeletonApplication.git
- cd ZendSkeletonApplication
- php composer.phar selfupdate
- php composer.phar install
- cd ../
- cd BrZend
- composer install --dev --no-interaction
- cd ..
- sudo cp -R BrZend/ ZendSkeletonApplication/module/BrZend
- cd ZendSkeletonApplication
- mkdir -p module/BrZend/build/logs


script:
- cd ../ZendSkeletonApplication/module/BrZend/tests
<<<<<<< HEAD
- sudo phpunit --coverage-clover ../build/logs/clover.xml
=======
- phpunit --coverage-clover ../../../build/logs/clover.xml
- sudo cp -R ../../../build/ ../build
- cd ../
- ls -a
>>>>>>> ffe8fb07819df78e1c6858fae632944c081ab492

after_script:
- ../../vendor/bin/coveralls -v
