<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BrZend\Module'                        => __DIR__ . '/Module.php',
    'BrZend\Controller\IndexController' => __DIR__ . '/src/BrZend/Controller/IndexController.php',
    'BrZendTest\Framework\TestCase'        => __DIR__ . '/tests/BrZend/Framework/TestCase.php',
    'BrZendTest\SampleTest'                => __DIR__ . '/tests/BrZend/SampleTest.php',
);
